
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 15 03:54:54 CST 2020
//----------------------------------------------------

package Backend.FlexYCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SCANFID = 46;
  public static final int CLASSID = 4;
  public static final int SWITCHID = 6;
  public static final int INDICADORFLOAT = 43;
  public static final int SCANNERID = 9;
  public static final int ELSEIDVB = 31;
  public static final int VOIDID = 8;
  public static final int CASEID = 13;
  public static final int DOID = 82;
  public static final int FORID = 78;
  public static final int PYID = 32;
  public static final int MAYOR = 67;
  public static final int BREAKID = 10;
  public static final int NEWID = 11;
  public static final int CONSOLEWRITEID = 25;
  public static final int IMPORTID = 3;
  public static final int SIMIGUAL = 55;
  public static final int PROGRAMAID = 38;
  public static final int NUMERO = 70;
  public static final int SELECTID = 29;
  public static final int DOIDVB = 18;
  public static final int JAVAID = 2;
  public static final int LOOPID = 17;
  public static final int FALSE = 73;
  public static final int NOT = 68;
  public static final int CORCHETEABRE = 60;
  public static final int SUBID = 27;
  public static final int MULTI = 53;
  public static final int ELSEID = 81;
  public static final int INDICADORCHAR = 45;
  public static final int SIMMENOS = 52;
  public static final int PRINFID = 40;
  public static final int FLOATID = 76;
  public static final int SOUTID = 5;
  public static final int CONTINUEID = 37;
  public static final int INPUTID = 33;
  public static final int COMA = 77;
  public static final int INTID = 74;
  public static final int PARABRE = 61;
  public static final int CORCHETECIERRA = 59;
  public static final int PARCIERRA = 62;
  public static final int TRUE = 72;
  public static final int DIMID = 28;
  public static final int WRITELNID = 26;
  public static final int IGUAL = 69;
  public static final int IFID = 80;
  public static final int NEXTLINEID = 12;
  public static final int RETURNID = 83;
  public static final int TOID = 15;
  public static final int CHAR = 48;
  public static final int DOSPUNTOS = 63;
  public static final int PUNTOYCOMA = 57;
  public static final int DIV = 54;
  public static final int MENOS = 51;
  public static final int CASEVBID = 30;
  public static final int DEFID = 35;
  public static final int NEXTID = 87;
  public static final int MENOR = 66;
  public static final int INDICADORINT = 44;
  public static final int IFIDVB = 21;
  public static final int CINID = 41;
  public static final int WHILEID = 79;
  public static final int EOF = 0;
  public static final int CONSOLEREADID = 24;
  public static final int THENID = 20;
  public static final int WHILEIDVB = 19;
  public static final int ENDID = 22;
  public static final int MENORIGUAL = 64;
  public static final int OR = 85;
  public static final int COMILLA = 71;
  public static final int error = 1;
  public static final int SIMMAS = 50;
  public static final int ID = 47;
  public static final int FORIDVB = 16;
  public static final int PUBLICID = 7;
  public static final int LLAVECIERRA = 58;
  public static final int CHARID = 75;
  public static final int DEFAULTID = 86;
  public static final int MAYORIGUAL = 65;
  public static final int ASID = 23;
  public static final int LLAVEABRE = 56;
  public static final int STRING = 49;
  public static final int SIMY = 88;
  public static final int INCLUDEID = 39;
  public static final int PRINTID = 34;
  public static final int AND = 84;
  public static final int INRANGEID = 36;
  public static final int VBID = 14;
  public static final int MAINID = 42;
}

