/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

import Backend.LectorArchivo;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.StringReader;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author astridmc
 */
public class Principal extends javax.swing.JFrame {

    boolean editor = false;
    int indice = 1;
    static String codFuente="";
    static String cod3D="";
    static String optimizado="";

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        panelEditor.setVisible(false);
        diseño();
    }

    int compiladorUso;
    ArrayList<String> formatos = new ArrayList();
    ArrayList<Editor> documentos = new ArrayList();
    ArrayList<File> files = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        imagenPanel = new javax.swing.JPanel();
        pnlOpciones = new javax.swing.JTabbedPane();
        panelEditor = new javax.swing.JPanel();
        panelArchivos = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pnlCod3D = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pnlOptimizacion = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pnlAssembler = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accionJugador = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnNuevo = new javax.swing.JMenuItem();
        btnAbrir = new javax.swing.JMenuItem();
        btnGuardar = new javax.swing.JMenuItem();
        btnGuardarComo = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        btnLenguajes = new javax.swing.JMenu();
        btnCod3D = new javax.swing.JMenuItem();
        btnCodOpt = new javax.swing.JMenuItem();
        btnAssembler = new javax.swing.JMenuItem();
        btnEjecutar = new javax.swing.JMenu();
        btnEjecutar3Dcod = new javax.swing.JMenuItem();
        btnEjecutarOptimizado = new javax.swing.JMenuItem();
        btnEjecutarAssembler = new javax.swing.JMenuItem();
        btnLALR = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(27, 46, 93));

        imagenPanel.setBackground(new java.awt.Color(83, 8, 78));
        imagenPanel.setForeground(new java.awt.Color(83, 8, 78));
        imagenPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imagenPanelComponentResized(evt);
            }
        });

        pnlOpciones.setFont(new java.awt.Font("URW Bookman L", 1, 18)); // NOI18N

        panelEditor.setBackground(new java.awt.Color(173, 238, 254));

        panelArchivos.setBackground(new java.awt.Color(173, 238, 254));
        panelArchivos.setFont(new java.awt.Font("Waree", 0, 20)); // NOI18N
        panelArchivos.setOpaque(true);
        panelArchivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                panelArchivosKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelArchivosKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelEditorLayout = new javax.swing.GroupLayout(panelEditor);
        panelEditor.setLayout(panelEditorLayout);
        panelEditorLayout.setHorizontalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE))
        );
        panelEditorLayout.setVerticalGroup(
            panelEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );

        pnlOpciones.addTab("programa", panelEditor);

        javax.swing.GroupLayout pnlCod3DLayout = new javax.swing.GroupLayout(pnlCod3D);
        pnlCod3D.setLayout(pnlCod3DLayout);
        pnlCod3DLayout.setHorizontalGroup(
            pnlCod3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        pnlCod3DLayout.setVerticalGroup(
            pnlCod3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCod3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCod3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlOpciones.addTab("Codigo En 3 Direcciones", jPanel2);

        jPanel3.setFont(new java.awt.Font("URW Bookman L", 1, 18)); // NOI18N

        javax.swing.GroupLayout pnlOptimizacionLayout = new javax.swing.GroupLayout(pnlOptimizacion);
        pnlOptimizacion.setLayout(pnlOptimizacionLayout);
        pnlOptimizacionLayout.setHorizontalGroup(
            pnlOptimizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        pnlOptimizacionLayout.setVerticalGroup(
            pnlOptimizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOptimizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlOptimizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlOpciones.addTab("Optimizacion", jPanel3);

        javax.swing.GroupLayout pnlAssemblerLayout = new javax.swing.GroupLayout(pnlAssembler);
        pnlAssembler.setLayout(pnlAssemblerLayout);
        pnlAssemblerLayout.setHorizontalGroup(
            pnlAssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        pnlAssemblerLayout.setVerticalGroup(
            pnlAssemblerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAssembler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAssembler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlOpciones.addTab("Assembler", jPanel4);

        javax.swing.GroupLayout imagenPanelLayout = new javax.swing.GroupLayout(imagenPanel);
        imagenPanel.setLayout(imagenPanelLayout);
        imagenPanelLayout.setHorizontalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpciones)
                .addContainerGap())
        );
        imagenPanelLayout.setVerticalGroup(
            imagenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOpciones)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(4, 35, 74));

        accionJugador.setFont(new java.awt.Font("URW Bookman L", 1, 18)); // NOI18N
        accionJugador.setForeground(new java.awt.Color(254, 254, 254));
        accionJugador.setText("Seccion Errores:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(accionJugador)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accionJugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jMenuBar1.setBackground(new java.awt.Color(120, 217, 221));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(70, 51));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 40));

        jMenu1.setBackground(new java.awt.Color(77, 183, 175));
        jMenu1.setForeground(new java.awt.Color(1, 1, 1));
        jMenu1.setText(" ARCHIVO ");
        jMenu1.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N
        jMenu1.setOpaque(true);

        btnNuevo.setBackground(new java.awt.Color(185, 240, 234));
        btnNuevo.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(btnNuevo);

        btnAbrir.setBackground(new java.awt.Color(143, 235, 220));
        btnAbrir.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(btnAbrir);

        btnGuardar.setBackground(new java.awt.Color(185, 240, 234));
        btnGuardar.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(btnGuardar);

        btnGuardarComo.setBackground(new java.awt.Color(143, 235, 220));
        btnGuardarComo.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnGuardarComo.setText("Guardar Como");
        btnGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(btnGuardarComo);

        btnSalir.setBackground(new java.awt.Color(185, 240, 234));
        btnSalir.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        btnLenguajes.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 2, 0));
        btnLenguajes.setForeground(new java.awt.Color(1, 1, 1));
        btnLenguajes.setText("Generar Codigo");
        btnLenguajes.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N

        btnCod3D.setBackground(new java.awt.Color(185, 240, 234));
        btnCod3D.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnCod3D.setText("Codigo en 3 Direcciones");
        btnCod3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCod3DActionPerformed(evt);
            }
        });
        btnLenguajes.add(btnCod3D);

        btnCodOpt.setBackground(new java.awt.Color(185, 240, 234));
        btnCodOpt.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnCodOpt.setText("Codigo Optimizado");
        btnCodOpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodOptActionPerformed(evt);
            }
        });
        btnLenguajes.add(btnCodOpt);

        btnAssembler.setBackground(new java.awt.Color(185, 240, 234));
        btnAssembler.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnAssembler.setText("Codigo Assembler");
        btnAssembler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssemblerActionPerformed(evt);
            }
        });
        btnLenguajes.add(btnAssembler);

        jMenuBar1.add(btnLenguajes);

        btnEjecutar.setBackground(new java.awt.Color(77, 183, 175));
        btnEjecutar.setForeground(new java.awt.Color(1, 1, 1));
        btnEjecutar.setText(" EJECUTAR ");
        btnEjecutar.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N
        btnEjecutar.setOpaque(true);

        btnEjecutar3Dcod.setBackground(new java.awt.Color(185, 240, 234));
        btnEjecutar3Dcod.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnEjecutar3Dcod.setText("Codigo en 3 direcciones");
        btnEjecutar3Dcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutar3DcodActionPerformed(evt);
            }
        });
        btnEjecutar.add(btnEjecutar3Dcod);

        btnEjecutarOptimizado.setBackground(new java.awt.Color(143, 235, 220));
        btnEjecutarOptimizado.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnEjecutarOptimizado.setText("Optimizado");
        btnEjecutarOptimizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarOptimizadoActionPerformed(evt);
            }
        });
        btnEjecutar.add(btnEjecutarOptimizado);

        btnEjecutarAssembler.setBackground(new java.awt.Color(185, 240, 234));
        btnEjecutarAssembler.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        btnEjecutarAssembler.setText("Assembler");
        btnEjecutarAssembler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarAssemblerActionPerformed(evt);
            }
        });
        btnEjecutar.add(btnEjecutarAssembler);

        jMenuBar1.add(btnEjecutar);

        btnLALR.setForeground(new java.awt.Color(1, 1, 1));
        btnLALR.setText(" VER ");
        btnLALR.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N
        jMenuBar1.add(btnLALR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(imagenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    JLabel imagen = new JLabel();
    String fondo = "src/Frontend/Imagenes/fondo2.jpg";
    ImageIcon portada = new ImageIcon(fondo);
    private void imagenPanelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imagenPanelComponentResized
        if (imagenPanel.getComponents().length > 0) {
            imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
            imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
            imagenPanel.remove(imagen);
            imagenPanel.add(imagen);

        }
    }//GEN-LAST:event_imagenPanelComponentResized

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        String nombre = "nuevo " + indice;
        if (editor == false) {
            if (nombre == null) {
                // nombrar.setVisible(false);
            } else {

                editor = true;
                panelEditor.setVisible(true);
            }
        }
        indice++;
        verificarExistenciaTab(nombre, null);
        formatos.add(nombre);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        System.out.println("entrandi archivo");
        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("TEXT FILES", "mlg");
        fileChooser.setFileFilter(imgFilter);
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.CANCEL_OPTION) {
            File fileName = fileChooser.getSelectedFile();
            if ((fileName == null) || (fileName.getName().equals(""))) {
            } else {
                try {
                    verificarExistenciaTab(fileName.getName(), fileName);
                } catch (Exception e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(null, "Error cargando Archivo");
                }

                if (editor == false) {
                    editor = true;
                    panelEditor.setVisible(true);

                }
                // txt.setText(fileName.getAbsolutePath());
            }
        }

    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        int indice = panelArchivos.getSelectedIndex();
        int i;

        for (i = 0; i < documentos.size(); i++) {
            System.out.println(documentos.size());
            if (documentos.get(i).getNombre() != null) {
                if (documentos.get(i).getNombre().equals(panelArchivos.getTitleAt(indice))) {
                    String texto = documentos.get(i).ObtenerTexto();
                    File archivo = documentos.get(i).getDocumento();
                    LectorArchivo lector = new LectorArchivo();
                    lector.GuardarTexto(archivo, texto);
                    panelArchivos.setTitleAt(indice, lector.nombre);
                    documentos.get(i).setNombre(lector.nombre);
                    documentos.get(i).setDocumento(lector.doc);
                    panelArchivos.setTabComponentAt(indice, createTabHead(lector.nombre));
                    break;
                }
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarComoActionPerformed
        int i;
        int index = panelArchivos.getSelectedIndex();
        if (panelArchivos.getComponentCount() > 0) {
            System.out.println(panelArchivos.getTitleAt(index));
            System.out.println(panelArchivos.getTabCount());
            for (i = 0; i < documentos.size(); i++) {
                if (panelArchivos.getTitleAt(index).equals(documentos.get(i).getNombre())) {
                    System.out.println("encontrado");
                    LectorArchivo lector = new LectorArchivo();
                    String texto = documentos.get(i).ObtenerTexto();
                    if (lector.GuardarArchivo(texto)) {
                        documentos.get(i).setNombre(lector.nombre);
                        documentos.get(i).setDocumento(lector.doc);
                        verificarExistenciaTab(lector.nombre, lector.doc);
                    }
                    break;
                }
            }
        }

    }//GEN-LAST:event_btnGuardarComoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEjecutar3DcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutar3DcodActionPerformed
        LectorArchivo lector = new LectorArchivo();
            String texto = cod3D;
            if (lector.GuardarArchivosCreados(cod3D, 1)) {
                
            }
    }//GEN-LAST:event_btnEjecutar3DcodActionPerformed

    private void btnEjecutarOptimizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarOptimizadoActionPerformed
        LectorArchivo lector = new LectorArchivo();
        String texto = cod3D;
        if (lector.GuardarArchivosCreados(optimizado, 2)) {
                
        }
    }//GEN-LAST:event_btnEjecutarOptimizadoActionPerformed

    private void btnEjecutarAssemblerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarAssemblerActionPerformed
        LectorArchivo lector = new LectorArchivo();
        String texto = cod3D;
        if (lector.GuardarArchivosCreados(codFuente, 2)) {
                
        }
    }//GEN-LAST:event_btnEjecutarAssemblerActionPerformed

    private void panelArchivosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelArchivosKeyTyped

    }//GEN-LAST:event_panelArchivosKeyTyped

    private void panelArchivosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelArchivosKeyPressed
        /*
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter imgFilter = new FileNameExtensionFilter("TEXT FILES", "len");
        fileChooser.setFileFilter(imgFilter);
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.CANCEL_OPTION) {
            File fileName = fileChooser.getSelectedFile();
            if ((fileName == null) || (fileName.getName().equals(""))) {
            } else {
                try {

                    //AnalizadorLexico lexico = new AnalizadorLexico(new BufferedReader(new StringReader(ManejadorArchivo.LeerArchivo(fileName.getPath()))));
                    //parser parser1 = new parser(lexico);
                    //parser1.parse();
                } catch (Exception ex) {
                    System.out.println("error...");
                    ex.printStackTrace();

                }
            }
        }*/
    
    }//GEN-LAST:event_panelArchivosKeyPressed

    private void btnCod3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCod3DActionPerformed
         int i;
        int index = panelArchivos.getSelectedIndex();
        if (panelArchivos.getComponentCount() > 0) {
            System.out.println(panelArchivos.getTitleAt(index));
            System.out.println(panelArchivos.getTabCount());
            for (i = 0; i < documentos.size(); i++) {
                if (panelArchivos.getTitleAt(index).equals(documentos.get(i).getNombre())) {
                    System.out.println("encontrado");
                    LectorArchivo lector = new LectorArchivo();
                    codFuente = documentos.get(i).ObtenerTexto();
                    break;
                }
            }
        }else{
            codFuente="";
        }
        
        if(codFuente.equals("")){
            JOptionPane.showMessageDialog(this, "No se Encuentra el codigo Fuente");
        }else{
            cod3D="hola";
            Editor editor = new Editor(cod3D, false);
            pnlCod3D.setLayout(new GridLayout(1, 1));
            pnlCod3D.add(editor);
        }
    }//GEN-LAST:event_btnCod3DActionPerformed

    private void btnCodOptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodOptActionPerformed
      if(cod3D.equals("")){
            JOptionPane.showMessageDialog(this, "No se Encuentra el codigo Fuente");
        }else{
            System.out.println("ENCONTRADO.......");
            optimizado = "holaopt";
            Editor editor = new Editor(optimizado, false);
            pnlOptimizacion.setLayout(new GridLayout(1, 1));
            pnlOptimizacion.add(editor);
        }
    }//GEN-LAST:event_btnCodOptActionPerformed

    private void btnAssemblerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssemblerActionPerformed
      
        
        if(optimizado.equals("")){
            JOptionPane.showMessageDialog(this, "No se Encuentra el codigo Fuente");
        }else{
            System.out.println("ENCONTRADO.......");
            Editor editor = new Editor("holaAssembler", false);
            pnlAssembler.setLayout(new GridLayout(1, 1));
            pnlAssembler.add(editor);
        }
    }//GEN-LAST:event_btnAssemblerActionPerformed

    void diseño() {
        setTitle("COMPILADOR");
        setLocation(200, 100);
        setIconImage(new ImageIcon("src/Frontend/Imagenes/icono.png").getImage());
        imagen.setBounds(0, 0, imagenPanel.getWidth(), imagenPanel.getHeight());
        imagen.setIcon(new ImageIcon(portada.getImage().getScaledInstance(imagenPanel.getWidth(), imagenPanel.getHeight(), Image.SCALE_SMOOTH)));
        imagenPanel.add(imagen);
    }

    /**
     * @param args the command line arguments
     */
    public JPanel createTabHead(String title) {
        JPanel pnlTab = new JPanel();
        pnlTab.setLayout(new BoxLayout(pnlTab, BoxLayout.LINE_AXIS));
        pnlTab.setOpaque(false);
        JButton btnClose = new JButton("x");
        JLabel lblTitle = new JLabel(title + "    ");
        btnClose.setBorderPainted(false);
        btnClose.setOpaque(false);

        btnClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int i;
                int nom = panelArchivos.getSelectedIndex();
                System.out.println(panelArchivos.getTitleAt(nom));
                for (i = 0; i <= panelArchivos.getTabCount() - 1; i++) {
                    if (panelArchivos.getTitleAt(nom) != null) {
                        if (panelArchivos.getTitleAt(nom).equals(documentos.get(i).getNombre())) {
                            break;
                        }
                    }
                }
                if (JOptionPane.showConfirmDialog(panelArchivos, "DESEA GUARDAR CAMBIOS AL ARCHIVO?") == 0) {
                    panelArchivos.removeTabAt(i);
                    String texto = documentos.get(i).ObtenerTexto();
                    File archivo = documentos.get(i).getDocumento();
                    LectorArchivo lector = new LectorArchivo();
                    lector.GuardarTexto(archivo, texto);
                    formatos.remove(i);
                    documentos.remove(i);
                } else {
                    panelArchivos.removeTabAt(nom);
                    if (panelArchivos.getComponentCount() == 0) {
                        formatos.clear();
                        documentos.clear();
                    }
                    try {
                        formatos.remove(i);
                        documentos.remove(i);
                    } catch (Exception ex) {
                    }
                }

            }
        });

        pnlTab.add(lblTitle);
        pnlTab.add(btnClose);
        return pnlTab;
    }

    public void verificarExistenciaTab(String nombre, File doc) {
        boolean aux = false;
        int i = 0;
        for (i = 0; i < formatos.size(); i++) {
            if (nombre.equals(formatos.get(i))) {
                aux = true;
                break;
            } else {
                aux = false;
            }
        }
        if (aux) {
            JOptionPane.showMessageDialog(rootPane, "ya tiene un documento con ese mismo nombre");
        } else if (!aux) {
            Editor editor;
            LectorArchivo lector = new LectorArchivo();
            if (doc != null) {
                editor = new Editor(lector.IdentificarDatos(doc.getAbsolutePath()));
            } else {
                editor = new Editor("");
            }
            editor.setNombre(nombre);
            editor.setDocumento(doc);
            documentos.add(editor);
            panelArchivos.addTab(nombre, editor);
            int index = panelArchivos.indexOfTab(nombre);
            panelArchivos.setTabComponentAt(index, createTabHead(nombre));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accionJugador;
    private javax.swing.JMenuItem btnAbrir;
    private javax.swing.JMenuItem btnAssembler;
    private javax.swing.JMenuItem btnCod3D;
    private javax.swing.JMenuItem btnCodOpt;
    private javax.swing.JMenu btnEjecutar;
    private javax.swing.JMenuItem btnEjecutar3Dcod;
    private javax.swing.JMenuItem btnEjecutarAssembler;
    private javax.swing.JMenuItem btnEjecutarOptimizado;
    private javax.swing.JMenuItem btnGuardar;
    private javax.swing.JMenuItem btnGuardarComo;
    private javax.swing.JMenu btnLALR;
    private javax.swing.JMenu btnLenguajes;
    private javax.swing.JMenuItem btnNuevo;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JPanel imagenPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane panelArchivos;
    private javax.swing.JPanel panelEditor;
    private javax.swing.JPanel pnlAssembler;
    private javax.swing.JPanel pnlCod3D;
    private javax.swing.JTabbedPane pnlOpciones;
    private javax.swing.JPanel pnlOptimizacion;
    // End of variables declaration//GEN-END:variables
}
